# Generated by Django 3.1.1 on 2020-10-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarrera', models.CharField(default='N/A', max_length=200)),
                ('numeroCiclos', models.IntegerField(default=5)),
                ('numeroCreditos', models.IntegerField(default=150)),
                ('codigoCarrera', models.CharField(default='N/A', max_length=10)),
                ('numeroDocentes', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField(default=5)),
                ('nombre', models.CharField(default='N/A', max_length=10)),
                ('NumeroEstudiantes', models.IntegerField(default=5)),
                ('carrera', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='holamundo.carrera')),
            ],
        ),
    ]
