# Generated by Django 3.1.1 on 2020-10-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holamundo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProfesor', models.CharField(default='N/A', max_length=200)),
                ('ApellidoProfesor', models.CharField(default='N/A', max_length=200)),
                ('Direccion', models.CharField(default='N/A', max_length=200)),
                ('edad', models.IntegerField(default=5)),
            ],
        ),
    ]
